/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_rm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Anonymous
 */
public final class Minuman extends javax.swing.JFrame {

    int count = 0;
    Connection con;
    Statement stmt;
    ResultSet rs, rs1;
    private String pass;

    /**
     * Creates new form Menu
     */
    public Minuman() {
        initComponents();
        FillBox();
    }

    public void FillBox() {
        try {
            String host = "jdbc:mysql://localhost:3306/kasir_rm";
            String user = "root";
            con = DriverManager.getConnection(host, user, pass);
            stmt = con.createStatement();
            stmt = con.createStatement();
            String query = "SELECT * FROM minuman";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String item = rs.getString("nama_minuman");
                Menu1.addItem(item);
                Menu2.addItem(item);
                Menu3.addItem(item);
                Menu4.addItem(item);
                Menu5.addItem(item);
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Menu1 = new javax.swing.JComboBox<>();
        jJumlah1 = new javax.swing.JTextField();
        jHarga1 = new javax.swing.JLabel();
        jSub1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSub2 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JComboBox<>();
        jJumlah2 = new javax.swing.JTextField();
        jHarga2 = new javax.swing.JLabel();
        jSub3 = new javax.swing.JLabel();
        Menu3 = new javax.swing.JComboBox<>();
        jJumlah3 = new javax.swing.JTextField();
        jHarga3 = new javax.swing.JLabel();
        jSub4 = new javax.swing.JLabel();
        Menu4 = new javax.swing.JComboBox<>();
        jJumlah4 = new javax.swing.JTextField();
        jHarga4 = new javax.swing.JLabel();
        jHarga5 = new javax.swing.JLabel();
        Menu5 = new javax.swing.JComboBox<>();
        jJumlah5 = new javax.swing.JTextField();
        jSub5 = new javax.swing.JLabel();
        jSimpan = new javax.swing.JButton();
        jBatal = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        jButtonSub = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KASIR RUMAH MAKAN REZA");

        Menu1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });

        jJumlah1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jJumlah1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jJumlah1.setToolTipText("");
        jJumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJumlah1ActionPerformed(evt);
            }
        });

        jHarga1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHarga1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jHarga1.setText("0");

        jSub1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSub1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSub1.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nama Item");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("@Harga");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jumlah(porsi)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SubTotal Harga");

        jSub2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSub2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSub2.setText("0");

        Menu2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ActionPerformed(evt);
            }
        });

        jJumlah2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jJumlah2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jJumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJumlah2ActionPerformed(evt);
            }
        });

        jHarga2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHarga2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jHarga2.setText("0");

        jSub3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSub3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSub3.setText("0");

        Menu3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu3ActionPerformed(evt);
            }
        });

        jJumlah3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jJumlah3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jHarga3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHarga3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jHarga3.setText("0");

        jSub4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSub4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSub4.setText("0");

        Menu4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu4ActionPerformed(evt);
            }
        });

        jJumlah4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jJumlah4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jHarga4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHarga4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jHarga4.setText("0");

        jHarga5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jHarga5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jHarga5.setText("0");

        Menu5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Menu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu5ActionPerformed(evt);
            }
        });

        jJumlah5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jJumlah5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSub5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSub5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSub5.setText("0");

        jSimpan.setBackground(new java.awt.Color(0, 255, 0));
        jSimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSimpan.setText("Selanjutnya");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jBatal.setBackground(new java.awt.Color(255, 255, 0));
        jBatal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBatal.setText("Kembali");
        jBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatalActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Total Harga");

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButtonSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSub.setText("Menghitung Harga");
        jButtonSub.setToolTipText("");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Minuman");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(399, 399, 399)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jHarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jHarga3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(jHarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Menu3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Menu5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Menu4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jHarga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jHarga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(588, 588, 588)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(jSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(210, 210, 210)))
                            .addGap(5, 5, 5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(629, 629, 629)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSub)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jJumlah3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jJumlah4)
                                        .addComponent(jJumlah5))
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSub5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(jSub4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSub3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(9, 9, 9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSimpan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jJumlah2)
                                .addGap(62, 62, 62)
                                .addComponent(jSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jHarga1, jHarga2, jHarga3, jHarga4, jHarga5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jJumlah1, jJumlah2, jJumlah3, jJumlah4, jJumlah5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBatal, jSimpan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jHarga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Menu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jJumlah2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jJumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jJumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSub5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jJumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Menu1, Menu4, Menu5, jButtonSub, jHarga1, jHarga2, jHarga3, jHarga4, jHarga5, jJumlah1, jJumlah2, jJumlah3, jJumlah4, jJumlah5, jSub1, jSub2, jSub3, jSub4, jSub5});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jJumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJumlah1ActionPerformed

    }//GEN-LAST:event_jJumlah1ActionPerformed

    private void Menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ActionPerformed
        try {
            String query = "SELECT * FROM minuman where nama_minuman=? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, (String) Menu2.getSelectedItem());
            ResultSet rset = st.executeQuery();
            while (rset.next()) {
                jHarga2.setText(rset.getString("harga_minuman"));
            }
        } catch (SQLException error) {

        }
    }//GEN-LAST:event_Menu2ActionPerformed

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        try {
            String query = "SELECT * FROM minuman where nama_minuman=? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, (String) Menu1.getSelectedItem());
            ResultSet rset = st.executeQuery();
            while (rset.next()) {
                jHarga1.setText(rset.getString("harga_minuman"));
            }
        } catch (SQLException error) {

        }
    }//GEN-LAST:event_Menu1ActionPerformed

    private void jBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatalActionPerformed
        Makanan _makanan = new Makanan();
        _makanan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBatalActionPerformed

    private void Menu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu5ActionPerformed
        try {
            String query = "SELECT * FROM minuman where nama_minuman=? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, (String) Menu5.getSelectedItem());
            ResultSet rset = st.executeQuery();
            while (rset.next()) {
                jHarga5.setText(rset.getString("harga_minuman"));
            }
        } catch (SQLException error) {

        }
    }//GEN-LAST:event_Menu5ActionPerformed

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        String id_num;
        String total_beli = jTotal.getText();

        int id = 0;
        try {
            String host = "jdbc:mysql://localhost:3306/kasir_rm";
            String user = "root";
            con = DriverManager.getConnection(host, user, pass);
            stmt = con.createStatement();
            stmt = con.createStatement();
            String query = "SELECT id_transaksi FROM transaksi";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                id++;
            }
            System.out.println(id);
            //id++;
            id_num = Integer.toString(id);
            String sql = "UPDATE transaksi SET " + "total_minuman = '" + total_beli + "' "
                    + "WHERE id_transaksi ='" + id_num + "'";
            stmt.executeUpdate(sql);
            System.out.println("Insert complete.");
            count++;

            Pembayaran _bayar = new Pembayaran();
            _bayar.setVisible(true);
            this.dispose();

            if (count == 0) {
                JOptionPane.showMessageDialog(null, "Data Yang Disimpan Belum Lengkap !");
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_jSimpanActionPerformed

    private void Menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu4ActionPerformed
        try {
            String query = "SELECT * FROM minuman where nama_minuman=? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, (String) Menu4.getSelectedItem());
            ResultSet rset = st.executeQuery();
            while (rset.next()) {
                jHarga4.setText(rset.getString("harga_minuman"));
            }
        } catch (SQLException error) {

        }
    }//GEN-LAST:event_Menu4ActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        if ("0".equals(jHarga1.getText())) {
            jJumlah1.setText("0");
        }
        if ("0".equals(jHarga2.getText())) {
            jJumlah2.setText("0");
        }
        if ("0".equals(jHarga3.getText())) {
            jJumlah3.setText("0");
        }
        if ("0".equals(jHarga4.getText())) {
            jJumlah4.setText("0");
        }
        if ("0".equals(jHarga5.getText())) {
            jJumlah5.setText("0");
        }

        if ("".equals(jJumlah1.getText())) {
            jJumlah1.setText("0");
        }
        if ("".equals(jJumlah2.getText())) {
            jJumlah2.setText("0");
        }
        if ("".equals(jJumlah3.getText())) {
            jJumlah3.setText("0");
        }
        if ("".equals(jJumlah4.getText())) {
            jJumlah4.setText("0");
        }
        if ("".equals(jJumlah5.getText())) {
            jJumlah5.setText("0");
        }
        String Sub1 = Integer.toString(Integer.parseInt(jHarga1.getText()) * Integer.parseInt(jJumlah1.getText()));
        jSub1.setText(Sub1);

        String Sub2 = Integer.toString(Integer.parseInt(jHarga2.getText()) * Integer.parseInt(jJumlah2.getText()));
        jSub2.setText(Sub2);

        String Sub3 = Integer.toString(Integer.parseInt(jHarga3.getText()) * Integer.parseInt(jJumlah3.getText()));
        jSub3.setText(Sub3);

        String Sub4 = Integer.toString(Integer.parseInt(jHarga4.getText()) * Integer.parseInt(jJumlah4.getText()));
        jSub4.setText(Sub4);

        String Sub5 = Integer.toString(Integer.parseInt(jHarga5.getText()) * Integer.parseInt(jJumlah5.getText()));
        jSub5.setText(Sub5);
        
        //Total
        int st1 = Integer.parseInt(jSub1.getText());
        int st2 = Integer.parseInt(jSub2.getText());
        int st3 = Integer.parseInt(jSub3.getText());
        int st4 = Integer.parseInt(jSub4.getText());
        int st5 = Integer.parseInt(jSub5.getText());
        String Total = Integer.toString(st1 + st2 + st3 + st4 + st5);
        jTotal.setText(Total);
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void Menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu3ActionPerformed
        try {
            String query = "SELECT * FROM minuman where nama_minuman=? ";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, (String) Menu3.getSelectedItem());
            ResultSet rset = st.executeQuery();
            while (rset.next()) {
                jHarga3.setText(rset.getString("harga_minuman"));
            }
        } catch (SQLException error) {

        }
    }//GEN-LAST:event_Menu3ActionPerformed

    private void jJumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJumlah2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Minuman().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Menu1;
    private javax.swing.JComboBox<String> Menu2;
    private javax.swing.JComboBox<String> Menu3;
    private javax.swing.JComboBox<String> Menu4;
    private javax.swing.JComboBox<String> Menu5;
    private javax.swing.JButton jBatal;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JLabel jHarga1;
    private javax.swing.JLabel jHarga2;
    private javax.swing.JLabel jHarga3;
    private javax.swing.JLabel jHarga4;
    private javax.swing.JLabel jHarga5;
    private javax.swing.JTextField jJumlah1;
    private javax.swing.JTextField jJumlah2;
    private javax.swing.JTextField jJumlah3;
    private javax.swing.JTextField jJumlah4;
    private javax.swing.JTextField jJumlah5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jSimpan;
    private javax.swing.JLabel jSub1;
    private javax.swing.JLabel jSub2;
    private javax.swing.JLabel jSub3;
    private javax.swing.JLabel jSub4;
    private javax.swing.JLabel jSub5;
    private javax.swing.JLabel jTotal;
    // End of variables declaration//GEN-END:variables
}
